name: Build with Gradle

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        cache-read-only: ${{ github.event_name == 'pull_request' }} # don't write to the cache from PRs
        arguments: build
    - name: Upload Plugin Artifact
      uses: actions/upload-artifact@v3
      with:
        name: RokuHorses
        path: build/libs/*.jar
